import { z } from "zod";

export const PortSchema = z.object({
  id: z.string(),
  name: z.string(),
  type: z.enum(["image", "video", "text", "number", "json"]),
  direction: z.enum(["input", "output"]),
  isArray: z.boolean().optional(),
});

export const NodeSchema = z.object({
  id: z.string().uuid(),
  type: z.string(),
  position: z.object({ x: z.number(), y: z.number() }),
  data: z.object({
    providerId: z.string().optional(),
    modelId: z.string().optional(),
    label: z.string(),
    params: z.record(z.unknown()),
    retryCount: z.number().int().min(0).max(3).default(1),
    timeoutMs: z.number().int().min(10000).max(1800000).default(300000),
    isAutoGenerated: z.boolean().optional(),
  }),
  inputs: z.array(PortSchema),
  outputs: z.array(PortSchema),
});

export const EdgeSchema = z.object({
  id: z.string().uuid(),
  source: z.string().uuid(),
  sourceHandle: z.string(),
  target: z.string().uuid(),
  targetHandle: z.string(),
});

export const WorkflowGraphSchema = z.object({
  version: z.literal(1),
  nodes: z.array(NodeSchema).max(100),
  edges: z.array(EdgeSchema),
});

export type Port = z.infer<typeof PortSchema>;
export type WorkflowNode = z.infer<typeof NodeSchema>;
export type WorkflowEdge = z.infer<typeof EdgeSchema>;
export type WorkflowGraph = z.infer<typeof WorkflowGraphSchema>;
